### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Cluelesshobo** [SFort/MC-invisframes#1]
When you throw a snowball at an item frame, the client crashes if the client has the mod installed. The server does not crash; if only the server has the mod the client will not crash.

**Comment by SFort** [comment]
ty, for the report [2.0.1](https://github.com/SFort/MC-invisframes/releases/download/r2.0.1/invisframes-2.0.1.jar) should fix it
and I've added a config to allow making frames invis with snowballs
