### ISSUE TITLE
Enchanted books and items not displayed correctly

### ISSUE THREAD

**Issue by d4rkm0nkey** [SFort/MC-invisframes#2]
When I use the mod, enchanted books in item frames look like normal books and enchanted items look like normal items.

I am using Sodium and Iris.

**Comment by SFort** [comment]
Yup this does seem to be a conflict
sry for assuming invalid i just didn't think this could happen

**Comment by SFort** [comment]
do you have better dropped items installed?

**Comment by d4rkm0nkey** [comment]
No I have not. My mods:

Animal Feeding Trough
Architect's Palette Fabric
Architectury
Artificial Foliage
Bamboo Tweaks
Cardinal Components API
Color Unchained
Dehydration
EditSign
EnvironmentZ
Extra Pieces
Fabric API
Fabric Language Kotlin
FerriteCore
Gilded Netherite
Gunpowder
Gunpowder Currency
Gunpowder Signshop
Invisible Frames
Iris
Item Scroller
Krypton
LambDynamicLights
Lithium
MaLiLib
Mannequins
Mo' Structures
Mo'Enchantments
Mobs Attempt Parkour
Mod Menu
Oh, How the Crafting Has Tabled!
Ok Zoomer
Phosphor
Puddles
Repurposed Structures
Shop Visualizer
Sodium
TridentReturn
Trinkets

**Comment by d4rkm0nkey** [comment]
When I remove Invisible Frames it works again.

**Comment by SFort** [comment]
ye it's a conflict between iris and invis frames for sure but i'm having a lot of trouble figuring out how

**Comment by SFort** [comment]
i don't see it on  your list but just in case
got Indium installed?

**Comment by SFort** [comment]
(ye no wasn't indium either)

**Comment by SFort** [comment]
It's an incompatability between invis frames, lithium, iris(or possibly the dev version of sodium they bundle)
could be retaled to IrisShaders/Iris#198
I can't fix this in invisframes and i don't have the time to debug this any further
so maybe bring this up on the iris/lithium issue tracker see what they think.
(please refrance it here if you do so, if you don't i'll probably open the issues when i get back, which could be a while)

**Comment by SFort** [comment]
At this point i have deleated a lot of comments because every time i did a test there was a compleatly diffrent result

this issue only turns up when iris, invis frames, lithium, sodium are installed and additionally possibly for only certain versions

thanks for the report but this has been a nightware to debug

**Comment by d4rkm0nkey** [comment]
Thank you for fixing this so fast!! I am currently doing a Youtube video and your mod is so helpful for it!

**Comment by d4rkm0nkey** [comment]
But what did you exactly change except the version number?

**Comment by SFort** [comment]
see 64c1fef
practically all that's changed in v2.0.2
is the mappings ware updated from 1.16.2+build.1 to 1.17+build.5

**Comment by d4rkm0nkey** [comment]
ah ok. Can you release a fix for version 1.16.5 as well? I guess most people still play on it.

**Comment by SFort** [comment]
should be backwards compatible nothing was actually changed code wise

**Comment by d4rkm0nkey** [comment]
Yes, I tested it and it works! Thank you!

**Comment by d4rkm0nkey** [comment]
hmm I am confused. It only works sometimes...
Started the game four times without changing any mod. Two times it worked and two times not.

**Comment by SFort** [comment]
amazing. theres nothing more i can really do though.
you're gonna have to ask the devs of the other mods.
(maybe make sure all the mods are updated?)

**Comment by SFort** [comment]
@d4rkm0nkey as this issue is still a mystery in case you can still reproduce it.
mind giving the newest version a try with setting the item check to server?
