### ISSUE TITLE
Infinite Amethyst Shards

### ISSUE THREAD

**Issue by BruhBruhBruhMoment** [SFort/MC-invisframes#5]
I don't know why but if I just shift left click the item frame twice it will give me a shard and also work if I don't have any shards.

**Comment by BruhBruhBruhMoment** [comment]
Shift Right click makes it work as intended but Shift + Left click makes any item frame a shard farm.

**Comment by SFort** [comment]
You got charm installed?

**Comment by BruhBruhBruhMoment** [comment]
thats probably it then lol. Wasnt aware of the conflict.

**Comment by SFort** [comment]
Well it's not hard to fix thought it would have been by now. running latest version of charm?

**Comment by SFort** [comment]
nvm just checked theive not fixed it

**Comment by BruhBruhBruhMoment** [comment]
yeah i have both for a server but I don't want infinite crystal shards so.

**Comment by SFort** [comment]
ye i'll do a PR to their mod, so soon.

**Comment by SFort** [comment]
especially since it has the same bug with other mods including fabrication. just a bit more convoluted then punching

**Comment by SFort** [comment]
dunno if they have a config but if they do disabling "Clear Item Frames" will fix it untill it's done properly. thanks for bringing to my attention that this is still a bug

**Comment by BruhBruhBruhMoment** [comment]
hey I tried uninstalling the mod from the server and it seems to have fixed the problem but I wanna test something.
 I need to test if it breaks the vanilla client, or if you have it installed client side, if it still works.

**Comment by SFort** [comment]
it'll work kindof, invisible frames without items will be visable untill you put a item in them that's it though

**Comment by BruhBruhBruhMoment** [comment]
but the invisible item frames work on a server that does not have it installed

**Comment by SFort** [comment]
[Fabrication](https://github.com/unascribed/Fabrication) now fixes this issue for charm ([refrenced commit](https://github.com/unascribed/Fabrication/commit/79ff5181a4345dccff7e156bdcb85b7e200503ee))

so feel free to thank unascribed for fixing charms issue
